### PR TITLE
added Javascript code to prevent the right click context menu from ap…

### PR DESCRIPTION
**Pull request by Andrew-WMDE**
added Javascript code to prevent the right click context menu from appearing

### CODE REVIEW

**Comment by thiemowmde** [comment]
Uh, seems hacky, but probably the only thing that can be done. Isn't there a central point in this code base where JavaScript is initialized? It doesn't look like this to me.

**Comment by Andrew-WMDE** [comment]
I didn't see one therefore I applied the code to the head template.

**Comment by KaiNissen** [comment]
could be outsourced into a .js file, though

**Comment by tobijat** [comment]
rebased the patch on top of master to check if the tests are passing now

**Pull request merged**
